Update GeofenceBootReceiver for Android 12 support
CrossGeeks/GeofencePlugin pull request #39
Opened 2021-12-14 09:04 UTC by striboldt

For Android 12 it is now mandatory to explicit supply a value for android:exported for intent filters.

2021-12-15 06:59 UTC, GerliP approved these changes

2021-12-15 10:33 UTC, nikolajskov approved these changes

2022-01-11 18:08 UTC, rdelrosario approved these changes

2022-08-25 18:25 UTC, Tim-Rossiter requested changes
nevermind

2022-08-25 18:27 UTC, Tim-Rossiter approved these changes

2022-08-25 20:20 UTC, merged